/* tslint:disable */
/* eslint-disable */
/**
 * Armada Automated Ordering API
 * The v2 API exposes the Armada delivery platform to merchant partners. Every request is authenticated with a merchant-scoped API key + secret using HMAC-SHA256 request signing. All endpoints are idempotent to retry when the response is a network error; duplicate keys de-dupe on `reference`.  ## Authentication  Send every request with three headers:  - `Authorization: Key <api_key_value>` - `x-armada-timestamp: <milliseconds since epoch>` - `x-armada-signature: <hex HMAC-SHA256>`  The signature is `HMAC_SHA256(secret, \"${timestamp}.${method}.${path}.${body}\")`. For `GET` requests the body is the empty string. The signature must arrive within 30 seconds of the timestamp.  ## Rate limits  Every response carries:  - `X-RateLimit-Limit` — the ceiling for this request\'s category - `X-RateLimit-Remaining` — how many calls remain in the current window - `X-RateLimit-Reset` — unix seconds when the window resets  On 429 the `Retry-After` header is set. Default ceilings: 300 reads / minute, 60 writes / minute, per API key. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@armadadelivery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DeliveryRequestDestination } from './delivery-request-destination';
// May contain unused imports in some cases
// @ts-ignore
import type { DeliveryRequestOrigin } from './delivery-request-origin';

/**
 * 
 * @export
 * @interface EstimateRequest
 */
export interface EstimateRequest {
    /**
     * 
     * @type {string}
     * @memberof EstimateRequest
     */
    'origin_format': EstimateRequestOriginFormatEnum;
    /**
     * 
     * @type {DeliveryRequestOrigin}
     * @memberof EstimateRequest
     */
    'origin': DeliveryRequestOrigin;
    /**
     * 
     * @type {string}
     * @memberof EstimateRequest
     */
    'destination_format': EstimateRequestDestinationFormatEnum;
    /**
     * 
     * @type {DeliveryRequestDestination}
     * @memberof EstimateRequest
     */
    'destination': DeliveryRequestDestination;
}

export const EstimateRequestOriginFormatEnum = {
    LocationFormat: 'location_format',
    BranchFormat: 'branch_format'
} as const;

export type EstimateRequestOriginFormatEnum = typeof EstimateRequestOriginFormatEnum[keyof typeof EstimateRequestOriginFormatEnum];
export const EstimateRequestDestinationFormatEnum = {
    LocationFormat: 'location_format',
    KuwaitFormat: 'kuwait_format',
    BahrainFormat: 'bahrain_format',
    KsaFormat: 'ksa_format',
    KsaShortFormat: 'ksa_short_format'
} as const;

export type EstimateRequestDestinationFormatEnum = typeof EstimateRequestDestinationFormatEnum[keyof typeof EstimateRequestDestinationFormatEnum];


