/* tslint:disable */
/* eslint-disable */
/**
 * Armada Automated Ordering API
 * The v2 API exposes the Armada delivery platform to merchant partners. Every request is authenticated with a merchant-scoped API key + secret using HMAC-SHA256 request signing. All endpoints are idempotent to retry when the response is a network error; duplicate keys de-dupe on `reference`.  ## Authentication  Send every request with three headers:  - `Authorization: Key <api_key_value>` - `x-armada-timestamp: <milliseconds since epoch>` - `x-armada-signature: <hex HMAC-SHA256>`  The signature is `HMAC_SHA256(secret, \"${timestamp}.${method}.${path}.${body}\")`. For `GET` requests the body is the empty string. The signature must arrive within 30 seconds of the timestamp.  ## Rate limits  Every response carries:  - `X-RateLimit-Limit` — the ceiling for this request\'s category - `X-RateLimit-Remaining` — how many calls remain in the current window - `X-RateLimit-Reset` — unix seconds when the window resets  On 429 the `Retry-After` header is set. Default ceilings: 300 reads / minute, 60 writes / minute, per API key. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@armadadelivery.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Invoice
 */
export interface Invoice {
    /**
     * 
     * @type {string}
     * @memberof Invoice
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Invoice
     */
    'invoiceNo'?: string;
    /**
     * 
     * @type {string}
     * @memberof Invoice
     */
    'type'?: InvoiceTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Invoice
     */
    'status'?: InvoiceStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof Invoice
     */
    'amount'?: number;
    /**
     * 
     * @type {string}
     * @memberof Invoice
     */
    'currency'?: string;
    /**
     * 
     * @type {number}
     * @memberof Invoice
     */
    'ordersCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof Invoice
     */
    'deliveryTripsCount'?: number;
    /**
     * 
     * @type {string}
     * @memberof Invoice
     */
    'periodBegin'?: string;
    /**
     * 
     * @type {string}
     * @memberof Invoice
     */
    'periodEnd'?: string;
    /**
     * 
     * @type {string}
     * @memberof Invoice
     */
    'dueOn'?: string;
    /**
     * 
     * @type {string}
     * @memberof Invoice
     */
    'createdAt'?: string;
}

export const InvoiceTypeEnum = {
    Regular: 'REGULAR',
    CustomerOrder: 'CUSTOMER_ORDER',
    Wallet: 'WALLET',
    TopupWallet: 'TOPUP_WALLET',
    RefundWallet: 'REFUND_WALLET',
    Refund: 'REFUND',
    TapWallet: 'TAP_WALLET'
} as const;

export type InvoiceTypeEnum = typeof InvoiceTypeEnum[keyof typeof InvoiceTypeEnum];
export const InvoiceStatusEnum = {
    Issued: 'ISSUED',
    Paid: 'PAID',
    Pending: 'PENDING',
    Sent: 'SENT',
    Canceled: 'CANCELED',
    Authorized: 'AUTHORIZED'
} as const;

export type InvoiceStatusEnum = typeof InvoiceStatusEnum[keyof typeof InvoiceStatusEnum];


